# SPDX-License-Identifier: PMPL-1.0-or-later

name = "ZeroProb"
uuid = "f9e8c2e0-8b4a-4d5f-9a3c-1e2d3c4b5a6f"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1.9"
Distributions = "0.25"
StatsBase = "0.34"
Plots = "1.39"
Makie = "0.20"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
